#pragma checksum "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\ReceiveQuestion.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c922905119d8ad85bc5aabe81e44607304425331"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_ReceiveQuestion), @"mvc.1.0.view", @"/Views/Home/ReceiveQuestion.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/ReceiveQuestion.cshtml", typeof(AspNetCore.Views_Home_ReceiveQuestion))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"c922905119d8ad85bc5aabe81e44607304425331", @"/Views/Home/ReceiveQuestion.cshtml")]
    public class Views_Home_ReceiveQuestion : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\ReceiveQuestion.cshtml"
  
    ViewData["Title"] = "ReceiveQuestion";

#line default
#line hidden
            BeginContext(107, 92, true);
            WriteLiteral("<h1>ReceiveQuestion</h1>\r\n\r\n<h3>Tack för din fråga, vi återkommer så snabbt som möjligt</h3>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
