#pragma checksum "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a8f960328184f07c2306f5b881ff5fad43bf4f41"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_index), @"mvc.1.0.view", @"/Views/Home/index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/index.cshtml", typeof(AspNetCore.Views_Home_index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a8f960328184f07c2306f5b881ff5fad43bf4f41", @"/Views/Home/index.cshtml")]
    public class Views_Home_index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml"
  
    ViewData["Title"] = "index";

#line default
#line hidden
            BeginContext(43, 26, true);
            WriteLiteral("\r\n<h1>index</h1>\r\n\r\n<ul>\r\n");
            EndContext();
#line 9 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml"
     foreach (var name in ViewBag.NameList)
    {


#line default
#line hidden
            BeginContext(123, 12, true);
            WriteLiteral("        <li>");
            EndContext();
            BeginContext(136, 4, false);
#line 12 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml"
       Write(name);

#line default
#line hidden
            EndContext();
            BeginContext(140, 7, true);
            WriteLiteral("</li>\r\n");
            EndContext();
#line 13 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml"
    }

#line default
#line hidden
            BeginContext(154, 9, true);
            WriteLiteral("</ul>\r\n\r\n");
            EndContext();
#line 16 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml"
 if (ViewBag.Number > 2)
{

#line default
#line hidden
            BeginContext(192, 17, true);
            WriteLiteral("    <p>Värdet är ");
            EndContext();
            BeginContext(210, 14, false);
#line 18 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml"
            Write(ViewBag.Number);

#line default
#line hidden
            EndContext();
            BeginContext(224, 22, true);
            WriteLiteral(" och större än 2</p>\r\n");
            EndContext();
#line 19 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml"
}
else
{

#line default
#line hidden
            BeginContext(258, 34, true);
            WriteLiteral("    <p>Värdet är mindre än 2</p>\r\n");
            EndContext();
#line 23 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreRazor\Views\Home\index.cshtml"
}

#line default
#line hidden
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
