#pragma checksum "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreModels\Views\Home\index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9780671d32f8bc35f803842248b1e691e9e1cb1a"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_index), @"mvc.1.0.view", @"/Views/Home/index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/index.cshtml", typeof(AspNetCore.Views_Home_index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"9780671d32f8bc35f803842248b1e691e9e1cb1a", @"/Views/Home/index.cshtml")]
    public class Views_Home_index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<ASPNETCoreModels.Models.Student>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreModels\Views\Home\index.cshtml"
  
    ViewData["Title"] = "index";

#line default
#line hidden
            BeginContext(83, 18, true);
            WriteLiteral("\r\n<p>Ditt namn är ");
            EndContext();
            BeginContext(102, 10, false);
#line 7 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreModels\Views\Home\index.cshtml"
           Write(Model.Name);

#line default
#line hidden
            EndContext();
            BeginContext(112, 19, true);
            WriteLiteral(" och din email är: ");
            EndContext();
            BeginContext(132, 11, false);
#line 7 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreModels\Views\Home\index.cshtml"
                                         Write(Model.Email);

#line default
#line hidden
            EndContext();
            BeginContext(143, 32, true);
            WriteLiteral("</p>\r\n<p>Ditt telefonnummer är: ");
            EndContext();
            BeginContext(176, 11, false);
#line 8 "C:\Users\Cheesecake\Documents\CMS18\ASP.NET MVC 1\Lektioner\ASPNETCoreModels\Views\Home\index.cshtml"
                     Write(Model.Phone);

#line default
#line hidden
            EndContext();
            BeginContext(187, 4, true);
            WriteLiteral("</p>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<ASPNETCoreModels.Models.Student> Html { get; private set; }
    }
}
#pragma warning restore 1591
